### ISSUE TITLE
1.5.1-SNAPSHOT fails in project

### ISSUE THREAD

**Issue by sejensen** [cquiroz/play-emberjs#12]
Hi

SBT cannot find the snapshot eventhough it is listed at one of the urls it tries. The latest release is 1.4 and do not have the ember features that I use.

Is there something wrong with the snapshot build, or pom file?

Heres is the error I get

[warn]  module not found: com.ketalo.play.plugins#emberjs;1.5.1-SNAPSHOT
[warn] ==== typesafe-ivy-releases: tried
[warn]   http://repo.typesafe.com/typesafe/ivy-releases/com.ketalo.play.plugins/emberjs/scala_2.10/sbt_0.13/1.5.1-SNAPSHOT/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   http://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.ketalo.play.plugins/emberjs/scala_2.10/sbt_0.13/1.5.1-SNAPSHOT/ivys/ivy.xml
[warn] ==== local: tried
[warn]   /Users/sejensen/.ivy2/local/com.ketalo.play.plugins/emberjs/scala_2.10/sbt_0.13/1.5.1-SNAPSHOT/ivys/ivy.xml
[warn] ==== activator-local: tried
[warn]   file:/Users/sejensen/Development/Frameworks/activator-1.1.2/repository/com.ketalo.play.plugins/emberjs/scala_2.10/sbt_0.13/1.5.1-SNAPSHOT/ivys/ivy.xml
[warn] ==== public: tried
[warn]   http://repo1.maven.org/maven2/com/ketalo/play/plugins/emberjs_2.10_0.13/1.5.1-SNAPSHOT/emberjs-1.5.1-SNAPSHOT.pom
[warn] ==== typesafe-releases: tried
[warn]   http://repo.typesafe.com/typesafe/releases/com/ketalo/play/plugins/emberjs_2.10_0.13/1.5.1-SNAPSHOT/emberjs-1.5.1-SNAPSHOT.pom
[warn] ==== typesafe-ivy-releasez: tried
[warn]   http://repo.typesafe.com/typesafe/ivy-releases/com.ketalo.play.plugins/emberjs/scala_2.10/sbt_0.13/1.5.1-SNAPSHOT/ivys/ivy.xml
[warn] ==== Typesafe repository: tried
[warn]   http://repo.typesafe.com/typesafe/releases/com/ketalo/play/plugins/emberjs_2.10_0.13/1.5.1-SNAPSHOT/emberjs-1.5.1-SNAPSHOT.pom
[warn] ==== Sonatype snapshots: tried
[warn]   http://oss.sonatype.org/content/repositories/snapshots/com/ketalo/play/plugins/emberjs_2.10_0.13/1.5.1-SNAPSHOT/emberjs-1.5.1-SNAPSHOT.pom
[warn] ==== Sonatype OSS Releases: tried
[warn]   https://oss.sonatype.org/content/repositories/releases/com/ketalo/play/plugins/emberjs_2.10_0.13/1.5.1-SNAPSHOT/emberjs-1.5.1-SNAPSHOT.pom
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.ketalo.play.plugins#emberjs;1.5.1-SNAPSHOT: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]      com.ketalo.play.plugins:emberjs:1.5.1-SNAPSHOT (sbtVersion=0.13, scalaVersion=2.10)
[warn]
sbt.ResolveException: unresolved dependency: com.ketalo.play.plugins#emberjs;1.5.1-SNAPSHOT: not found
    at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:217)
    at sbt.IvyActions$$anonfun$update$1.apply(IvyActions.scala:126)
    at sbt.IvyActions$$anonfun$update$1.apply(IvyActions.scala:125)
    at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:116)
    at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:116)
    at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:104)
    at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:51)
    at sbt.IvySbt$$anon$3.call(Ivy.scala:60)
    at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:98)
    at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:81)
    at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:102)
    at xsbt.boot.Using$.withResource(Using.scala:11)

Kind regards
Steffen

**Comment by krumpi** [comment]
Hi

I published a fresh copy of the plugin. Can you try it?

**Comment by sejensen** [comment]
Hi

It seems that I am not even able to build the sample-1.5.1, does that work in your end?

Have tried to clean my ivy cache without luck. I am using activator as build tool

Here is the sample stacktrace
sample-1.5.1$ activator compile
[info] Loading project definition from /Users/sejensen/Development/Scala/demo/play-emberjs/sample-1.5.1/project
[warn]  module not found: com.ketalo.play.plugins#emberjs;1.5.1-SNAPSHOT
[warn] ==== typesafe-ivy-releases: tried
[warn]   http://repo.typesafe.com/typesafe/ivy-releases/com.ketalo.play.plugins/emberjs/scala_2.10/sbt_0.13/1.5.1-SNAPSHOT/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   http://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.ketalo.play.plugins/emberjs/scala_2.10/sbt_0.13/1.5.1-SNAPSHOT/ivys/ivy.xml
[warn] ==== local: tried
[warn]   /Users/sejensen/.ivy2/local/com.ketalo.play.plugins/emberjs/scala_2.10/sbt_0.13/1.5.1-SNAPSHOT/ivys/ivy.xml
[warn] ==== activator-local: tried
[warn]   file:/Users/sejensen/Development/Frameworks/activator-1.1.2/repository/com.ketalo.play.plugins/emberjs/scala_2.10/sbt_0.13/1.5.1-SNAPSHOT/ivys/ivy.xml
[warn] ==== public: tried
[warn]   http://repo1.maven.org/maven2/com/ketalo/play/plugins/emberjs_2.10_0.13/1.5.1-SNAPSHOT/emberjs-1.5.1-SNAPSHOT.pom
[warn] ==== typesafe-releases: tried
[warn]   http://repo.typesafe.com/typesafe/releases/com/ketalo/play/plugins/emberjs_2.10_0.13/1.5.1-SNAPSHOT/emberjs-1.5.1-SNAPSHOT.pom
[warn] ==== typesafe-ivy-releasez: tried
[warn]   http://repo.typesafe.com/typesafe/ivy-releases/com.ketalo.play.plugins/emberjs/scala_2.10/sbt_0.13/1.5.1-SNAPSHOT/ivys/ivy.xml
[warn] ==== Typesafe repository: tried
[warn]   http://repo.typesafe.com/typesafe/releases/com/ketalo/play/plugins/emberjs_2.10_0.13/1.5.1-SNAPSHOT/emberjs-1.5.1-SNAPSHOT.pom
[warn] ==== Sonatype snapshots: tried
[warn]   http://oss.sonatype.org/content/repositories/snapshots/com/ketalo/play/plugins/emberjs_2.10_0.13/1.5.1-SNAPSHOT/emberjs-1.5.1-SNAPSHOT.pom
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.ketalo.play.plugins#emberjs;1.5.1-SNAPSHOT: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]      com.ketalo.play.plugins:emberjs:1.5.1-SNAPSHOT (sbtVersion=0.13, scalaVersion=2.10)
[warn]
sbt.ResolveException: unresolved dependency: com.ketalo.play.plugins#emberjs;1.5.1-SNAPSHOT: not found
    at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:213)
    at sbt.IvyActions$$anonfun$update$1.apply(IvyActions.scala:122)
    at sbt.IvyActions$$anonfun$update$1.apply(IvyActions.scala:121)
    at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:116)
    at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:116)
    at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:104)
    at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:51)
    at sbt.IvySbt$$anon$3.call(Ivy.scala:60)
    at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:98)
    at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:81)
    at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:102)
    at xsbt.boot.Using$.withResource(Using.scala:11)
    at xsbt.boot.Using$.apply(Using.scala:10)
    at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:62)
    at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:52)

**Comment by krumpi** [comment]
This is odd, the last repository:
[warn] http://oss.sonatype.org/content/repositories/snapshots/com/ketalo/play/plugins/emberjs_2.10_0.13/1.5.1-SNAPSHOT/emberjs-1.5.1-SNAPSHOT.pom

Seems the correct one, let me try from scratch

**Comment by teroxik** [comment]
Hello I have the same problem. It worked well in May. But since beginning of June there is the problem described above. There are no code changes since end of April and the jar is still there. Only the version of sbt/activator/play has changed.

Kind regards,
Michal

**Comment by krumpi** [comment]
It is broken even for older builds like an version 0.1.1 project I have.
Something must have changed on sonatype

**Comment by sejensen** [comment]
Hi everyone

Seems like the fix was quite easy and it was really a annoying bug.

Just change to https for sonatype repository. And it worked here with activator 1.2.2 (play 2.3)

/Steffen

**Comment by krumpi** [comment]
Hi

Nice catch. I'll update the documentation accordingly
