### ISSUE TITLE
Not compiling handlebars templates under nested directory

### ISSUE THREAD

**Issue by 6qat** [cquiroz/play-emberjs#13]
The first time you put a template under a nested subdirectory (templates/somedirectory), it compiles correctly. The problem is when I change this template. The plugin does not figure out that the template changed and does not compile it again. In order to make it work, I need to restart the Play server.

**Comment by krumpi** [comment]
This is working for me. Are you in Windows?

**Comment by krumpi** [comment]
I put an update with some more logging indicating when it reads it from the cache and when it is compiled. Could you run your project against it?
