### ISSUE TITLE
The 1.6.1 snapshot is missing

### ISSUE THREAD

**Issue by huberts** [cquiroz/play-emberjs#14]
Hi!
The new version - 1.6.1 - is not available at https://oss.sonatype.org/content/repositories/snapshots/com/ketalo/play/plugins/emberjs_2.10_0.13/
Any chance to add it there?

**Comment by krumpi** [comment]
Hi

I just published, please check if it is working for you

Cheers

**Comment by huberts** [comment]
Nice, I will check it tomorrow. Great and thanks for your work!
