### ISSUE TITLE
Subtemplates are not rendred

### ISSUE THREAD

**Issue by Fliegendreck** [cquiroz/play-emberjs#4]
I am using play 2.1.3 and Scala 2.10.0 when i start the sample application (sample-1.0.0), i get the following output:

"Ember 1.0.0 Main template, including an inner one." 

The sub template is not rendered.

**Comment by krumpi** [comment]
I cannot reproduce it neither in 2.1.1 nor 2.1.3
Could you clean your project and try again?

**Comment by Fliegendreck** [comment]
I tried the same on a Linux machine and had no Problems. Maybe it is a Problem with Windows and/or cygwin

**Comment by krumpi** [comment]
It could be related to the way paths are handled in Windows. I only have OSX and Linux machines to test
