### ISSUE TITLE
Keywords as properties and variables in ember-1.2.0.for-rhino.js cause compilation errors

### ISSUE THREAD

**Issue by nullrocket** [cquiroz/play-emberjs#6]
Ember-1.2.0.for-rhino.js uses several keywords that cause template compilation to choke.  I know the polite thing to do would be to issue a pull request but I have diverged too far with my local changes for that to be useful and my git foo is weak. :)

I have it working locally by:

replacing .volatile with ["volatile"] 
this.string and string with astring
char and this.char with achar

**Comment by krumpi** [comment]
I couldn't find any reference to string that needed replacement, could you point out if you found any?

**Comment by nullrocket** [comment]
I commented on the lines in the commit, there are several references starting around line 29307.
