### ISSUE TITLE
Wrong information in README.md

### ISSUE THREAD

**Issue by zikolach** [cquiroz/play-emberjs#7]
Specified resolvers don't work:
`resolvers += "Sonatype releases" at "http://oss.sonatype.org/service/local/staging/deploy/maven2"`
Change them to following in README.md:
`resolvers += "Sonatype snapshots" at "http://oss.sonatype.org/content/repositories/snapshots/"`

And default Play 2.2.x build.sbt with emberJsVersion parameter liiks like this:

```
name := "Mapper"

version := "1.0-SNAPSHOT"

libraryDependencies ++= Seq(
  jdbc,
  anorm,
  cache
)

emberJsVersion := "1.2.0"

play.Project.playScalaSettings

```

**Comment by krumpi** [comment]
Hi

Thanks for noting these. Would you suggest to put your build.sbt besides or instead of the Build.scala sample?

**Comment by zikolach** [comment]
Hi,

I think besides, because it covers only latest Play version.
